import type { Profile, Job, MatchScore } from "../types/index.js";

export const DEMO_PROFILE: Profile = {
  id: "550e8400-e29b-41d4-a716-446655440000",
  userId: "660e8400-e29b-41d4-a716-446655440001",
  name: "Alex Chen",
  email: "alex.chen@example.com",
  title: "Senior Full-Stack Engineer",
  summary: "Experienced full-stack engineer with 7 years building scalable web applications. Passionate about AI/ML integration and developer tools. Led teams of 3-8 engineers shipping products used by 100K+ users.",
  location: "San Francisco, CA",
  skills: [
    { name: "TypeScript", category: "technical", level: "expert", yearsOfExperience: 6 },
    { name: "React", category: "technical", level: "expert", yearsOfExperience: 6 },
    { name: "Node.js", category: "technical", level: "advanced", yearsOfExperience: 5 },
    { name: "Python", category: "technical", level: "advanced", yearsOfExperience: 4 },
    { name: "PostgreSQL", category: "technical", level: "advanced", yearsOfExperience: 5 },
    { name: "AWS", category: "tool", level: "advanced", yearsOfExperience: 4 },
    { name: "Docker", category: "tool", level: "intermediate", yearsOfExperience: 3 },
    { name: "GraphQL", category: "technical", level: "advanced", yearsOfExperience: 3 },
    { name: "Machine Learning", category: "domain", level: "intermediate", yearsOfExperience: 2 },
    { name: "Team Leadership", category: "soft", level: "advanced" },
    { name: "System Design", category: "technical", level: "advanced" },
    { name: "CI/CD", category: "tool", level: "advanced", yearsOfExperience: 4 },
  ],
  experience: [
    {
      company: "TechCorp AI",
      title: "Senior Full-Stack Engineer",
      startDate: "2022-01",
      current: true,
      description: "Leading development of AI-powered developer tools platform",
      highlights: [
        "Architected real-time collaboration features serving 50K concurrent users",
        "Built ML pipeline for code suggestion engine with 85% acceptance rate",
        "Reduced API response times by 60% through query optimization and caching",
        "Mentored 4 junior engineers, 2 promoted to mid-level within a year",
      ],
      skills: ["TypeScript", "React", "Node.js", "Python", "PostgreSQL", "AWS"],
    },
    {
      company: "StartupXYZ",
      title: "Full-Stack Engineer",
      startDate: "2019-06",
      endDate: "2021-12",
      current: false,
      description: "Built core product features for B2B SaaS analytics platform",
      highlights: [
        "Developed real-time dashboard system processing 1M+ events/day",
        "Implemented GraphQL API layer reducing frontend data fetching by 40%",
        "Led migration from monolith to microservices architecture",
      ],
      skills: ["TypeScript", "React", "GraphQL", "Node.js", "Docker"],
    },
    {
      company: "WebAgency Co",
      title: "Frontend Developer",
      startDate: "2017-08",
      endDate: "2019-05",
      current: false,
      description: "Built responsive web applications for enterprise clients",
      highlights: [
        "Delivered 15+ client projects on time and within budget",
        "Established component library reducing development time by 30%",
      ],
      skills: ["React", "TypeScript", "CSS", "Figma"],
    },
  ],
  education: [
    {
      institution: "UC Berkeley",
      degree: "Bachelor of Science",
      field: "Computer Science",
      startDate: "2013-08",
      endDate: "2017-05",
      gpa: 3.7,
    },
  ],
  linkedinUrl: "https://linkedin.com/in/alexchen",
  portfolioUrl: "https://alexchen.dev",
  createdAt: "2024-01-15T10:00:00Z",
  updatedAt: "2024-06-20T14:30:00Z",
};

export const DEMO_JOBS: Job[] = [
  {
    id: "770e8400-e29b-41d4-a716-446655440010",
    title: "Staff Engineer, AI Platform",
    company: "Anthropic",
    location: "San Francisco, CA",
    remote: false,
    description: "Build the next generation of AI safety and alignment tools. Work on core infrastructure powering Claude and related systems.",
    requirements: [
      "8+ years of software engineering experience",
      "Strong TypeScript/Python skills",
      "Experience with ML systems and infrastructure",
      "Experience with distributed systems at scale",
      "Track record of technical leadership",
    ],
    niceToHaves: [
      "Experience with LLM fine-tuning",
      "Contributions to open-source AI projects",
      "Background in AI safety research",
    ],
    salaryMin: 250000,
    salaryMax: 400000,
    salaryCurrency: "USD",
    experienceLevel: "senior",
    employmentType: "full-time",
    skills: ["TypeScript", "Python", "Machine Learning", "Distributed Systems", "AWS"],
    postedDate: "2024-06-01T00:00:00Z",
    source: "careers-page",
    createdAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "770e8400-e29b-41d4-a716-446655440011",
    title: "Senior Frontend Engineer",
    company: "Stripe",
    location: "San Francisco, CA",
    remote: true,
    description: "Build beautiful, performant financial tools for millions of businesses. Work on Stripe Dashboard and developer-facing products.",
    requirements: [
      "5+ years of frontend engineering experience",
      "Expert-level React and TypeScript",
      "Experience with design systems",
      "Strong understanding of web performance",
      "Experience with financial or payments systems a plus",
    ],
    niceToHaves: [
      "Experience with Next.js",
      "Familiarity with payment APIs",
      "Accessibility (a11y) expertise",
    ],
    salaryMin: 200000,
    salaryMax: 320000,
    salaryCurrency: "USD",
    experienceLevel: "senior",
    employmentType: "full-time",
    skills: ["React", "TypeScript", "CSS", "Web Performance", "Design Systems"],
    postedDate: "2024-06-10T00:00:00Z",
    source: "careers-page",
    createdAt: "2024-06-10T00:00:00Z",
  },
  {
    id: "770e8400-e29b-41d4-a716-446655440012",
    title: "Full-Stack Engineer, Growth",
    company: "Vercel",
    location: "Remote",
    remote: true,
    description: "Drive growth through data-informed product development. Build features that help developers ship faster.",
    requirements: [
      "4+ years full-stack experience",
      "Proficiency in React and Node.js",
      "Experience with Next.js",
      "Data-driven mindset with A/B testing experience",
      "Strong product sense",
    ],
    niceToHaves: [
      "Experience with edge computing",
      "DevOps background",
      "Open-source contributions",
    ],
    salaryMin: 180000,
    salaryMax: 280000,
    salaryCurrency: "USD",
    experienceLevel: "mid",
    employmentType: "full-time",
    skills: ["React", "Node.js", "Next.js", "TypeScript", "PostgreSQL"],
    postedDate: "2024-06-15T00:00:00Z",
    source: "careers-page",
    createdAt: "2024-06-15T00:00:00Z",
  },
];

export const DEMO_MATCHES: MatchScore[] = [
  {
    id: "880e8400-e29b-41d4-a716-446655440020",
    profileId: DEMO_PROFILE.id,
    jobId: DEMO_JOBS[0]!.id,
    overallScore: 78,
    skillMatchScore: 82,
    experienceMatchScore: 75,
    educationMatchScore: 80,
    cultureFitScore: 76,
    skillGaps: [
      {
        skill: "Distributed Systems",
        required: true,
        profileLevel: "intermediate",
        requiredLevel: "advanced",
        gapSeverity: "moderate",
        suggestion: "Consider contributing to open-source distributed systems projects or take a course on distributed computing",
      },
      {
        skill: "ML Infrastructure",
        required: true,
        profileLevel: "intermediate",
        requiredLevel: "advanced",
        gapSeverity: "moderate",
        suggestion: "Build a personal project deploying ML models at scale, practice with tools like Ray or Kubeflow",
      },
    ],
    strengths: [
      "Strong TypeScript and Python combination",
      "ML experience with practical applications",
      "Technical leadership track record",
      "UC Berkeley CS background aligns well",
    ],
    reasoning: "Alex is a strong candidate for this role. The 7 years of experience and demonstrated ML integration work align well with Anthropic's needs. The main gaps are in distributed systems depth and dedicated ML infrastructure experience, but these are bridgeable given the strong foundation.",
    createdAt: "2024-06-20T15:00:00Z",
  },
  {
    id: "880e8400-e29b-41d4-a716-446655440021",
    profileId: DEMO_PROFILE.id,
    jobId: DEMO_JOBS[1]!.id,
    overallScore: 92,
    skillMatchScore: 95,
    experienceMatchScore: 90,
    educationMatchScore: 85,
    cultureFitScore: 88,
    skillGaps: [
      {
        skill: "Payment Systems",
        required: false,
        profileLevel: "none",
        requiredLevel: "intermediate",
        gapSeverity: "minor",
        suggestion: "Review Stripe's public documentation and build a sample integration to demonstrate domain familiarity",
      },
    ],
    strengths: [
      "Expert-level React and TypeScript - exceeds requirements",
      "Experience building real-time dashboards and data visualization",
      "Component library experience directly relevant to design systems",
      "Performance optimization track record",
    ],
    reasoning: "Excellent match. Alex's frontend expertise significantly exceeds the requirements. The real-time collaboration and dashboard experience maps directly to Stripe Dashboard work. Only minor gap is fintech domain experience.",
    createdAt: "2024-06-20T15:00:00Z",
  },
  {
    id: "880e8400-e29b-41d4-a716-446655440022",
    profileId: DEMO_PROFILE.id,
    jobId: DEMO_JOBS[2]!.id,
    overallScore: 88,
    skillMatchScore: 90,
    experienceMatchScore: 88,
    educationMatchScore: 85,
    cultureFitScore: 90,
    skillGaps: [],
    strengths: [
      "Full-stack React + Node.js experience matches perfectly",
      "Product-oriented mindset demonstrated in previous roles",
      "Experience with real-time features and data processing",
      "Over-qualified technically, which is positive for growth role",
    ],
    reasoning: "Strong match with slight overqualification. Alex has the full-stack skills, product thinking, and technical depth needed. The growth focus aligns with the data-driven dashboard work at TechCorp.",
    createdAt: "2024-06-20T15:00:00Z",
  },
];
